// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package pg

import (
	"context"
)

const deleteApiKey = `-- name: DeleteApiKey :execrows
DELETE FROM api_keys WHERE id = $1
`

// Revoke a key by id. :execrows lets the caller detect a missing id (0 rows).
func (q *Queries) DeleteApiKey(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteApiKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, name, prefix, key_hash, scope, created_at, last_used_at FROM api_keys WHERE key_hash = $1
`

// The per-request verification lookup: hash the presented bearer and find its key.
func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertApiKey = `-- name: InsertApiKey :one
INSERT INTO api_keys (name, prefix, key_hash, scope, created_at, last_used_at)
VALUES (
    $1, $2, $3, $4,
    $5, $6
)
RETURNING id, name, prefix, key_hash, scope, created_at, last_used_at
`

type InsertApiKeyParams struct {
	Name       string `json:"name"`
	Prefix     string `json:"prefix"`
	KeyHash    string `json:"key_hash"`
	Scope      string `json:"scope"`
	CreatedAt  int64  `json:"created_at"`
	LastUsedAt int64  `json:"last_used_at"`
}

// Stores a new API key. Only the SHA-256 hash of the secret is persisted (the full
// key is shown to the caller once and never stored); `prefix` is a non-secret
// fragment for display. RETURNING * yields the generated id.
func (q *Queries) InsertApiKey(ctx context.Context, arg InsertApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, insertApiKey,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Scope,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, name, prefix, key_hash, scope, created_at, last_used_at FROM api_keys ORDER BY id DESC
`

// Newest first, for the dashboard list (the secret is never returned, only metadata).
func (q *Queries) ListApiKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listApiKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.Scope,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApiKeyLastUsed = `-- name: UpdateApiKeyLastUsed :exec
UPDATE api_keys SET last_used_at = $1 WHERE id = $2
`

type UpdateApiKeyLastUsedParams struct {
	LastUsedAt int64 `json:"last_used_at"`
	ID         int64 `json:"id"`
}

// Best-effort touch of the last-used timestamp after a successful verification.
func (q *Queries) UpdateApiKeyLastUsed(ctx context.Context, arg UpdateApiKeyLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateApiKeyLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
