// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package pg

import (
	"context"
)

const deleteEventsBefore = `-- name: DeleteEventsBefore :execrows
DELETE FROM events WHERE occurred_at < $1
`

// Retention prune: drops events that occurred before the cutoff (unix seconds).
// :execrows reports how many rows were removed, for logging.
func (q *Queries) DeleteEventsBefore(ctx context.Context, cutoff int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEventsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEventBySequence = `-- name: GetEventBySequence :one
SELECT id, event_id, event_type, entity_type, entity_id, occurred_at, data FROM events WHERE id = $1
`

func (q *Queries) GetEventBySequence(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventBySequence, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.EntityType,
		&i.EntityID,
		&i.OccurredAt,
		&i.Data,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (event_id, event_type, entity_type, entity_id, occurred_at, data)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, event_id, event_type, entity_type, entity_id, occurred_at, data
`

type InsertEventParams struct {
	EventID    string `json:"event_id"`
	EventType  string `json:"event_type"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	OccurredAt int64  `json:"occurred_at"`
	Data       string `json:"data"`
}

// Appends one immutable event to the canonical stream. The generated id
// (sequence) and the stored row are returned so the caller can broadcast the
// just-committed event to live SSE subscribers. event_id is a caller-supplied
// UUID (unique); data is a JSON object.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.EventID,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.OccurredAt,
		arg.Data,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.EntityType,
		&i.EntityID,
		&i.OccurredAt,
		&i.Data,
	)
	return i, err
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT id, event_id, event_type, entity_type, entity_id, occurred_at, data FROM events
WHERE id > $1
  AND (event_type = $2 OR $2 = '')
  AND (entity_type = $3 OR $3 = '')
  AND (entity_id = $4 OR $4 = '')
ORDER BY id
LIMIT $5
`

type ListEventsAfterParams struct {
	After      int64  `json:"after"`
	EventType  string `json:"event_type"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	RowLimit   int32  `json:"row_limit"`
}

// The cursor read: every event whose sequence is greater than `after`, in stream
// order, with optional exact-match filters (an empty string disables that filter).
// Mirrors the ListTransactions optional-filter shape - the column is written first
// so sqlc infers a non-null type for each bound parameter, keeping the generated
// params struct byte-identical across SQLite and Postgres (row_limit aside, which
// the pg adapter casts to int32). row_limit caps the page size.
func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsAfter,
		arg.After,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.OccurredAt,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEvents = `-- name: ListRecentEvents :many
SELECT id, event_id, event_type, entity_type, entity_id, occurred_at, data FROM events ORDER BY id DESC LIMIT $1
`

// The most recent events, newest first. Powers "what just happened" views (the
// dashboard live feed) that want the tail of the stream without first discovering
// its head. Callers that want chronological order reverse the result.
func (q *Queries) ListRecentEvents(ctx context.Context, rowLimit int32) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listRecentEvents, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.OccurredAt,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
