// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: market.sql

package pg

import (
	"context"
)

const countMarketPoints = `-- name: CountMarketPoints :one
SELECT COUNT(*) FROM market_points WHERE series_id = $1
`

func (q *Queries) CountMarketPoints(ctx context.Context, seriesID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMarketPoints, seriesID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMarketSeries = `-- name: DeleteMarketSeries :execrows
DELETE FROM market_series WHERE id = $1
`

func (q *Queries) DeleteMarketSeries(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMarketSeries, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMarketSeriesPoints = `-- name: DeleteMarketSeriesPoints :exec
DELETE FROM market_points WHERE series_id = $1
`

func (q *Queries) DeleteMarketSeriesPoints(ctx context.Context, seriesID string) error {
	_, err := q.db.ExecContext(ctx, deleteMarketSeriesPoints, seriesID)
	return err
}

const getMarketSeries = `-- name: GetMarketSeries :one
SELECT id, provider, symbol, kind, currency, adjusted, meta
FROM market_series
WHERE id = $1
`

func (q *Queries) GetMarketSeries(ctx context.Context, id string) (MarketSeries, error) {
	row := q.db.QueryRowContext(ctx, getMarketSeries, id)
	var i MarketSeries
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Symbol,
		&i.Kind,
		&i.Currency,
		&i.Adjusted,
		&i.Meta,
	)
	return i, err
}

const latestMarketPoint = `-- name: LatestMarketPoint :one
SELECT series_id, date, value, fetched_at
FROM market_points
WHERE series_id = $1
ORDER BY date DESC
LIMIT 1
`

// The newest-dated cached point for a series. Returns sql.ErrNoRows when the
// series has never been fetched (cold cache); otherwise its date is the series'
// "as of" and its fetched_at is the last refresh time (a refresh upserts the
// whole window with one timestamp), which the read path uses for TTL freshness.
// Avoids a COALESCE(MAX(...)) aggregate, whose sqlc type inference differs across
// SQLite and Postgres and would break the struct-identity pgstore adapter.
func (q *Queries) LatestMarketPoint(ctx context.Context, seriesID string) (MarketPoint, error) {
	row := q.db.QueryRowContext(ctx, latestMarketPoint, seriesID)
	var i MarketPoint
	err := row.Scan(
		&i.SeriesID,
		&i.Date,
		&i.Value,
		&i.FetchedAt,
	)
	return i, err
}

const listMarketPoints = `-- name: ListMarketPoints :many
SELECT series_id, date, value, fetched_at
FROM market_points
WHERE series_id = $1
  AND ($2 = '' OR date >= $2)
  AND ($3 = '' OR date <= $3)
ORDER BY date
`

type ListMarketPointsParams struct {
	SeriesID string      `json:"series_id"`
	Since    interface{} `json:"since"`
	Until    interface{} `json:"until"`
}

// Points for a series within an optional [since, until] date window. An empty
// bound means unbounded on that side; ISO-8601 dates sort lexically.
func (q *Queries) ListMarketPoints(ctx context.Context, arg ListMarketPointsParams) ([]MarketPoint, error) {
	rows, err := q.db.QueryContext(ctx, listMarketPoints, arg.SeriesID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketPoint{}
	for rows.Next() {
		var i MarketPoint
		if err := rows.Scan(
			&i.SeriesID,
			&i.Date,
			&i.Value,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketSeries = `-- name: ListMarketSeries :many
SELECT id, provider, symbol, kind, currency, adjusted, meta
FROM market_series
ORDER BY id
`

func (q *Queries) ListMarketSeries(ctx context.Context) ([]MarketSeries, error) {
	rows, err := q.db.QueryContext(ctx, listMarketSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketSeries{}
	for rows.Next() {
		var i MarketSeries
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Symbol,
			&i.Kind,
			&i.Currency,
			&i.Adjusted,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateMarketPoints = `-- name: TruncateMarketPoints :exec
DELETE FROM market_points
`

func (q *Queries) TruncateMarketPoints(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateMarketPoints)
	return err
}

const truncateMarketSeries = `-- name: TruncateMarketSeries :exec
DELETE FROM market_series
`

func (q *Queries) TruncateMarketSeries(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateMarketSeries)
	return err
}

const upsertMarketPoint = `-- name: UpsertMarketPoint :exec
INSERT INTO market_points (series_id, date, value, fetched_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (series_id, date) DO UPDATE SET
    value      = excluded.value,
    fetched_at = excluded.fetched_at
`

type UpsertMarketPointParams struct {
	SeriesID  string `json:"series_id"`
	Date      string `json:"date"`
	Value     string `json:"value"`
	FetchedAt int64  `json:"fetched_at"`
}

func (q *Queries) UpsertMarketPoint(ctx context.Context, arg UpsertMarketPointParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketPoint,
		arg.SeriesID,
		arg.Date,
		arg.Value,
		arg.FetchedAt,
	)
	return err
}

const upsertMarketSeries = `-- name: UpsertMarketSeries :exec
INSERT INTO market_series (id, provider, symbol, kind, currency, adjusted, meta)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (id) DO UPDATE SET
    provider = excluded.provider,
    symbol   = excluded.symbol,
    kind     = excluded.kind,
    currency = excluded.currency,
    adjusted = excluded.adjusted,
    meta     = excluded.meta
`

type UpsertMarketSeriesParams struct {
	ID       string `json:"id"`
	Provider string `json:"provider"`
	Symbol   string `json:"symbol"`
	Kind     string `json:"kind"`
	Currency string `json:"currency"`
	Adjusted int64  `json:"adjusted"`
	Meta     string `json:"meta"`
}

func (q *Queries) UpsertMarketSeries(ctx context.Context, arg UpsertMarketSeriesParams) error {
	_, err := q.db.ExecContext(ctx, upsertMarketSeries,
		arg.ID,
		arg.Provider,
		arg.Symbol,
		arg.Kind,
		arg.Currency,
		arg.Adjusted,
		arg.Meta,
	)
	return err
}
