// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pg

import (
	"database/sql"
)

type Account struct {
	ID          string `json:"id"`
	OrgID       string `json:"org_id"`
	Name        string `json:"name"`
	Currency    string `json:"currency"`
	Balance     string `json:"balance"`
	BalanceDate int64  `json:"balance_date"`
	SyncedAt    int64  `json:"synced_at"`
	Source      string `json:"source"`
}

type ApiKey struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Prefix     string `json:"prefix"`
	KeyHash    string `json:"key_hash"`
	Scope      string `json:"scope"`
	CreatedAt  int64  `json:"created_at"`
	LastUsedAt int64  `json:"last_used_at"`
}

type Event struct {
	ID         int64  `json:"id"`
	EventID    string `json:"event_id"`
	EventType  string `json:"event_type"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	OccurredAt int64  `json:"occurred_at"`
	Data       string `json:"data"`
}

type MarketPoint struct {
	SeriesID  string `json:"series_id"`
	Date      string `json:"date"`
	Value     string `json:"value"`
	FetchedAt int64  `json:"fetched_at"`
}

type MarketSeries struct {
	ID       string `json:"id"`
	Provider string `json:"provider"`
	Symbol   string `json:"symbol"`
	Kind     string `json:"kind"`
	Currency string `json:"currency"`
	Adjusted int64  `json:"adjusted"`
	Meta     string `json:"meta"`
}

type Organization struct {
	ID      string `json:"id"`
	Domain  string `json:"domain"`
	Name    string `json:"name"`
	SfinUrl string `json:"sfin_url"`
}

type Plugin struct {
	ID                  int64  `json:"id"`
	Name                string `json:"name"`
	Runtime             string `json:"runtime"`
	Version             string `json:"version"`
	Enabled             int64  `json:"enabled"`
	GrantedCapabilities string `json:"granted_capabilities"`
	Config              string `json:"config"`
	CreatedAt           int64  `json:"created_at"`
	UpdatedAt           int64  `json:"updated_at"`
	LastStatus          int64  `json:"last_status"`
	LastError           string `json:"last_error"`
	LastRunAt           int64  `json:"last_run_at"`
	LastSuccessAt       int64  `json:"last_success_at"`
	NetGrants           string `json:"net_grants"`
}

type Rule struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Query      string `json:"query"`
	Labels     string `json:"labels"`
	Enabled    int64  `json:"enabled"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
	Extensions string `json:"extensions"`
}

type Setting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt int64  `json:"updated_at"`
}

type SyncLog struct {
	ID          int64          `json:"id"`
	StartedAt   int64          `json:"started_at"`
	CompletedAt sql.NullInt64  `json:"completed_at"`
	Status      string         `json:"status"`
	Error       sql.NullString `json:"error"`
}

type Transaction struct {
	ID            string `json:"id"`
	AccountID     string `json:"account_id"`
	Amount        string `json:"amount"`
	Pending       int64  `json:"pending"`
	Date          int64  `json:"date"`
	Description   string `json:"description"`
	Payee         string `json:"payee"`
	Memo          string `json:"memo"`
	SyncedAt      int64  `json:"synced_at"`
	Labels        string `json:"labels"`
	Extensions    string `json:"extensions"`
	Source        string `json:"source"`
	Relationships string `json:"relationships"`
}

type TransactionVersion struct {
	ID            int64  `json:"id"`
	TransactionID string `json:"transaction_id"`
	ChangeKind    string `json:"change_kind"`
	OccurredAt    int64  `json:"occurred_at"`
	Data          string `json:"data"`
}

type Webhook struct {
	ID            int64  `json:"id"`
	Url           string `json:"url"`
	Secret        string `json:"secret"`
	EventTypes    string `json:"event_types"`
	Enabled       int64  `json:"enabled"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
	LastStatus    int64  `json:"last_status"`
	LastError     string `json:"last_error"`
	LastAttemptAt int64  `json:"last_attempt_at"`
	LastSuccessAt int64  `json:"last_success_at"`
}
