// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pg

import (
	"database/sql"
)

type Account struct {
	ID          string `json:"id"`
	OrgID       string `json:"org_id"`
	Name        string `json:"name"`
	Currency    string `json:"currency"`
	Balance     string `json:"balance"`
	BalanceDate int64  `json:"balance_date"`
	SyncedAt    int64  `json:"synced_at"`
}

type Organization struct {
	ID      string `json:"id"`
	Domain  string `json:"domain"`
	Name    string `json:"name"`
	SfinUrl string `json:"sfin_url"`
}

type SyncLog struct {
	ID          int64          `json:"id"`
	StartedAt   int64          `json:"started_at"`
	CompletedAt sql.NullInt64  `json:"completed_at"`
	Status      string         `json:"status"`
	Error       sql.NullString `json:"error"`
}

type Transaction struct {
	ID          string `json:"id"`
	AccountID   string `json:"account_id"`
	Amount      string `json:"amount"`
	Pending     int64  `json:"pending"`
	Date        int64  `json:"date"`
	Description string `json:"description"`
	Payee       string `json:"payee"`
	Memo        string `json:"memo"`
	SyncedAt    int64  `json:"synced_at"`
	Tags        string `json:"tags"`
}
