// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pg

import (
	"context"
)

type Querier interface {
	CompleteSyncLog(ctx context.Context, arg CompleteSyncLogParams) error
	CountTransactions(ctx context.Context) (int64, error)
	CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (SyncLog, error)
	GetAccount(ctx context.Context, id string) (Account, error)
	GetOrganization(ctx context.Context, id string) (Organization, error)
	GetTransaction(ctx context.Context, id string) (Transaction, error)
	// transactions.id is the SimpleFIN transaction ID, so re-syncing the same
	// transaction is a no-op. This keeps polling idempotent.
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error)
	LatestSyncLog(ctx context.Context) (SyncLog, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListAccountsByOrg(ctx context.Context, orgID string) ([]Account, error)
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListSyncLogs(ctx context.Context, rowLimit int32) ([]SyncLog, error)
	// Returns the (id, tags) of every transaction that carries at least one tag. The
	// API explodes the JSON arrays in Go to build the tag vocabulary with per-tag
	// transaction counts, and reuses the same rows to strip a tag from every
	// transaction on delete. Done in Go (not SQL) to stay portable across SQLite and
	// Postgres (no JSON functions or dialect-specific aggregation). ORDER BY makes
	// the row order deterministic, so the spelling kept for a case-insensitively
	// duplicated tag is stable.
	ListTaggedTransactions(ctx context.Context) ([]ListTaggedTransactionsRow, error)
	// A bound of 0 disables that side of the date filter (so 0/0 returns all).
	// The column comparison is written first so sqlc infers an integer type for
	// the bound parameters from the `date` column.
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error)
	// Replaces the whole tag set for one transaction. tags is a JSON array of
	// strings; the API normalizes it before storing. :execrows lets the caller
	// detect a missing id (0 rows affected). The poller never touches tags, so this
	// is the only writer.
	UpdateTransactionTags(ctx context.Context, arg UpdateTransactionTagsParams) (int64, error)
	UpsertAccount(ctx context.Context, arg UpsertAccountParams) error
	UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) error
}

var _ Querier = (*Queries)(nil)
