// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package pg

import (
	"context"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (name, query, labels, enabled, created_at, updated_at)
VALUES (
    $1, $2, $3, $4,
    $5, $6
)
RETURNING id, name, query, labels, enabled, created_at, updated_at
`

type CreateRuleParams struct {
	Name      string `json:"name"`
	Query     string `json:"query"`
	Labels    string `json:"labels"`
	Enabled   int64  `json:"enabled"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

// A rule pairs a condition (a kasas search query) with an action (a JSON object
// of labels to apply on a match). The API validates the query and normalizes the
// labels before storing. RETURNING * yields the generated id and timestamps.
func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, createRule,
		arg.Name,
		arg.Query,
		arg.Labels,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.Labels,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :execrows
DELETE FROM rules WHERE id = $1
`

func (q *Queries) DeleteRule(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRule = `-- name: GetRule :one
SELECT id, name, query, labels, enabled, created_at, updated_at FROM rules WHERE id = $1
`

func (q *Queries) GetRule(ctx context.Context, id int64) (Rule, error) {
	row := q.db.QueryRowContext(ctx, getRule, id)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.Labels,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledRules = `-- name: ListEnabledRules :many
SELECT id, name, query, labels, enabled, created_at, updated_at FROM rules WHERE enabled = 1 ORDER BY id
`

// The deterministic id order makes rule precedence predictable when several
// rules write the same label key (later rules win).
func (q *Queries) ListEnabledRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Query,
			&i.Labels,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT id, name, query, labels, enabled, created_at, updated_at FROM rules ORDER BY id
`

func (q *Queries) ListRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Query,
			&i.Labels,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :execrows
UPDATE rules
SET name       = $1,
    query      = $2,
    labels     = $3,
    enabled    = $4,
    updated_at = $5
WHERE id = $6
`

type UpdateRuleParams struct {
	Name      string `json:"name"`
	Query     string `json:"query"`
	Labels    string `json:"labels"`
	Enabled   int64  `json:"enabled"`
	UpdatedAt int64  `json:"updated_at"`
	ID        int64  `json:"id"`
}

// Replaces the editable fields of a rule. :execrows lets the caller detect a
// missing id (0 rows affected).
func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRule,
		arg.Name,
		arg.Query,
		arg.Labels,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
