// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_versions.sql

package pg

import (
	"context"
)

const countTransactionVersions = `-- name: CountTransactionVersions :one
SELECT COUNT(*) FROM transaction_versions
WHERE transaction_id = $1
`

// Whether a transaction has any history yet. Backs the lazy baseline: the first
// time an existing transaction changes after this feature shipped, the writer
// synthesizes a v1 "imported" snapshot from its prior state. COUNT(*) is used (not
// an EXISTS/MAX) because sqlc infers it as int64 identically on SQLite and Postgres
// (see CountTransactions), keeping the pgstore adapter a plain pass-through.
func (q *Queries) CountTransactionVersions(ctx context.Context, transactionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionVersions, transactionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTransactionVersionsBefore = `-- name: DeleteTransactionVersionsBefore :execrows
DELETE FROM transaction_versions WHERE occurred_at < $1
`

// Retention prune: drops versions that occurred before the cutoff (unix seconds).
// :execrows reports how many rows were removed, for logging. Only runs when
// events.history_retention_days > 0; the default keeps history forever.
func (q *Queries) DeleteTransactionVersionsBefore(ctx context.Context, cutoff int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTransactionVersionsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTransactionVersionsByTransaction = `-- name: DeleteTransactionVersionsByTransaction :execrows
DELETE FROM transaction_versions WHERE transaction_id = $1
`

// Removes all history snapshots for one transaction. Used when a manual transaction
// is deleted: transaction_versions has no foreign key to transactions, so the row
// delete does not cascade here and the history would otherwise be orphaned. Runs in
// the same transaction as the DeleteTransaction call.
func (q *Queries) DeleteTransactionVersionsByTransaction(ctx context.Context, transactionID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTransactionVersionsByTransaction, transactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertTransactionVersion = `-- name: InsertTransactionVersion :one
INSERT INTO transaction_versions (transaction_id, change_kind, occurred_at, data)
VALUES (
    $1, $2, $3,
    $4
)
RETURNING id, transaction_id, change_kind, occurred_at, data
`

type InsertTransactionVersionParams struct {
	TransactionID string `json:"transaction_id"`
	ChangeKind    string `json:"change_kind"`
	OccurredAt    int64  `json:"occurred_at"`
	Data          string `json:"data"`
}

// Appends one immutable snapshot to a transaction's history. The generated id
// (insert order) and the stored row are returned. There is no per-transaction
// version number column: a transaction's versions are its rows ordered by id, and
// the API assigns the ordinal (v1, v2, ...) on read. data is a JSON object.
func (q *Queries) InsertTransactionVersion(ctx context.Context, arg InsertTransactionVersionParams) (TransactionVersion, error) {
	row := q.db.QueryRowContext(ctx, insertTransactionVersion,
		arg.TransactionID,
		arg.ChangeKind,
		arg.OccurredAt,
		arg.Data,
	)
	var i TransactionVersion
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ChangeKind,
		&i.OccurredAt,
		&i.Data,
	)
	return i, err
}

const listTransactionVersions = `-- name: ListTransactionVersions :many
SELECT id, transaction_id, change_kind, occurred_at, data FROM transaction_versions
WHERE transaction_id = $1
ORDER BY id
`

// One transaction's full history, oldest first. ORDER BY id is the version order
// (id is the monotonic insert sequence), so the caller assigns v1, v2, ... by
// position and diffs each snapshot against the previous one.
func (q *Queries) ListTransactionVersions(ctx context.Context, transactionID string) ([]TransactionVersion, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionVersions, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionVersion{}
	for rows.Next() {
		var i TransactionVersion
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.ChangeKind,
			&i.OccurredAt,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
