// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package pg

import (
	"context"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, account_id, amount, pending, date, description, payee, memo, synced_at FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Pending,
		&i.Date,
		&i.Description,
		&i.Payee,
		&i.Memo,
		&i.SyncedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :execrows
INSERT INTO transactions (
    id, account_id, amount, pending, date, description, payee, memo, synced_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9
)
ON CONFLICT (id) DO NOTHING
`

type InsertTransactionParams struct {
	ID          string `json:"id"`
	AccountID   string `json:"account_id"`
	Amount      string `json:"amount"`
	Pending     int64  `json:"pending"`
	Date        int64  `json:"date"`
	Description string `json:"description"`
	Payee       string `json:"payee"`
	Memo        string `json:"memo"`
	SyncedAt    int64  `json:"synced_at"`
}

// transactions.id is the SimpleFIN transaction ID, so re-syncing the same
// transaction is a no-op. This keeps polling idempotent.
func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertTransaction,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.Pending,
		arg.Date,
		arg.Description,
		arg.Payee,
		arg.Memo,
		arg.SyncedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, account_id, amount, pending, date, description, payee, memo, synced_at FROM transactions
WHERE (date >= $1 OR $1 = 0)
  AND (date <= $2 OR $2 = 0)
ORDER BY date DESC, id
LIMIT $4 OFFSET $3
`

type ListTransactionsParams struct {
	Since     int64 `json:"since"`
	Until     int64 `json:"until"`
	RowOffset int32 `json:"row_offset"`
	RowLimit  int32 `json:"row_limit"`
}

// A bound of 0 disables that side of the date filter (so 0/0 returns all).
// The column comparison is written first so sqlc infers an integer type for
// the bound parameters from the `date` column.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions,
		arg.Since,
		arg.Until,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Pending,
			&i.Date,
			&i.Description,
			&i.Payee,
			&i.Memo,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, account_id, amount, pending, date, description, payee, memo, synced_at FROM transactions
WHERE account_id = $1
  AND (date >= $2 OR $2 = 0)
  AND (date <= $3 OR $3 = 0)
ORDER BY date DESC, id
LIMIT $5 OFFSET $4
`

type ListTransactionsByAccountParams struct {
	AccountID string `json:"account_id"`
	Since     int64  `json:"since"`
	Until     int64  `json:"until"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByAccount,
		arg.AccountID,
		arg.Since,
		arg.Until,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Pending,
			&i.Date,
			&i.Description,
			&i.Payee,
			&i.Memo,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
