// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package pg

import (
	"context"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, account_id, amount, pending, date, description, payee, memo, synced_at, labels, extensions, source, relationships FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Pending,
		&i.Date,
		&i.Description,
		&i.Payee,
		&i.Memo,
		&i.SyncedAt,
		&i.Labels,
		&i.Extensions,
		&i.Source,
		&i.Relationships,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :execrows
INSERT INTO transactions (
    id, account_id, amount, pending, date, description, payee, memo, synced_at,
    source, labels, extensions, relationships
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, '{}', '{}', '[]'
)
ON CONFLICT (id) DO NOTHING
`

type InsertTransactionParams struct {
	ID          string `json:"id"`
	AccountID   string `json:"account_id"`
	Amount      string `json:"amount"`
	Pending     int64  `json:"pending"`
	Date        int64  `json:"date"`
	Description string `json:"description"`
	Payee       string `json:"payee"`
	Memo        string `json:"memo"`
	SyncedAt    int64  `json:"synced_at"`
	Source      string `json:"source"`
}

// transactions.id is the SimpleFIN transaction ID, so re-syncing the same
// transaction is a no-op. This keeps polling idempotent. labels and extensions
// are written as explicit empty objects, and relationships as an empty array, so
// new rows never depend on the column default (SQLite can't cheaply change a
// STRICT table's default; see the 00003, 00009 and 00012 migrations). source is
// the provenance of the row (which ingestion path produced it) and is a bound
// argument, not a literal, so a future bridge stamps its own; the poller passes
// "simplefin".
func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertTransaction,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.Pending,
		arg.Date,
		arg.Description,
		arg.Payee,
		arg.Memo,
		arg.SyncedAt,
		arg.Source,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listExtendedTransactions = `-- name: ListExtendedTransactions :many
SELECT id, extensions FROM transactions WHERE extensions <> '{}' ORDER BY id
`

type ListExtendedTransactionsRow struct {
	ID         string `json:"id"`
	Extensions string `json:"extensions"`
}

// Returns the (id, extensions) of every transaction carrying at least one
// extension. The API explodes the JSON objects in Go to build the extension
// vocabulary (one entry per distinct key, with a transaction count). Done in Go,
// like ListLabeledTransactions, to stay portable across SQLite and Postgres
// (json_each vs jsonb_each infer different column types, which would break the
// byte-identical pgstore adapter). ORDER BY makes the row order deterministic.
func (q *Queries) ListExtendedTransactions(ctx context.Context) ([]ListExtendedTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExtendedTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExtendedTransactionsRow{}
	for rows.Next() {
		var i ListExtendedTransactionsRow
		if err := rows.Scan(&i.ID, &i.Extensions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabeledTransactions = `-- name: ListLabeledTransactions :many
SELECT id, labels FROM transactions WHERE labels <> '{}' ORDER BY id
`

type ListLabeledTransactionsRow struct {
	ID     string `json:"id"`
	Labels string `json:"labels"`
}

// Returns the (id, labels) of every transaction that carries at least one label.
// The API explodes the JSON objects in Go to build the label vocabulary with
// per-pair transaction counts. Done in Go (not SQL) to stay portable across
// SQLite and Postgres: json_each (SQLite) and jsonb_each_text (Postgres) infer
// different column types, which would break the byte-identical pgstore adapter.
// Filtering and deletion, by contrast, are pushed down to SQL (see the
// per-dialect queries/{sqlite,postgres}/labels.sql). ORDER BY makes the row order
// deterministic.
func (q *Queries) ListLabeledTransactions(ctx context.Context) ([]ListLabeledTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLabeledTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabeledTransactionsRow{}
	for rows.Next() {
		var i ListLabeledTransactionsRow
		if err := rows.Scan(&i.ID, &i.Labels); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedTransactions = `-- name: ListRelatedTransactions :many
SELECT id, relationships FROM transactions WHERE relationships <> '[]' ORDER BY id
`

type ListRelatedTransactionsRow struct {
	ID            string `json:"id"`
	Relationships string `json:"relationships"`
}

// Returns the (id, relationships) of every transaction carrying at least one
// outbound edge. The API explodes the JSON arrays in Go to (a) build the inbound
// index (who points at a given transaction) and (b) build the relationship-kind
// vocabulary with per-kind counts. Done in Go, like ListLabeledTransactions and
// ListExtendedTransactions, to stay portable across SQLite and Postgres (json_each
// vs jsonb_each infer different column types, which would break the byte-identical
// pgstore adapter). ORDER BY makes the row order deterministic.
func (q *Queries) ListRelatedTransactions(ctx context.Context) ([]ListRelatedTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelatedTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelatedTransactionsRow{}
	for rows.Next() {
		var i ListRelatedTransactionsRow
		if err := rows.Scan(&i.ID, &i.Relationships); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, account_id, amount, pending, date, description, payee, memo, synced_at, labels, extensions, source, relationships FROM transactions
WHERE (date >= $1 OR $1 = 0)
  AND (date <= $2 OR $2 = 0)
ORDER BY date DESC, id
LIMIT $4 OFFSET $3
`

type ListTransactionsParams struct {
	Since     int64 `json:"since"`
	Until     int64 `json:"until"`
	RowOffset int32 `json:"row_offset"`
	RowLimit  int32 `json:"row_limit"`
}

// A bound of 0 disables that side of the date filter (so 0/0 returns all).
// The column comparison is written first so sqlc infers an integer type for
// the bound parameters from the `date` column.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions,
		arg.Since,
		arg.Until,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Pending,
			&i.Date,
			&i.Description,
			&i.Payee,
			&i.Memo,
			&i.SyncedAt,
			&i.Labels,
			&i.Extensions,
			&i.Source,
			&i.Relationships,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, account_id, amount, pending, date, description, payee, memo, synced_at, labels, extensions, source, relationships FROM transactions
WHERE account_id = $1
  AND (date >= $2 OR $2 = 0)
  AND (date <= $3 OR $3 = 0)
ORDER BY date DESC, id
LIMIT $5 OFFSET $4
`

type ListTransactionsByAccountParams struct {
	AccountID string `json:"account_id"`
	Since     int64  `json:"since"`
	Until     int64  `json:"until"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByAccount,
		arg.AccountID,
		arg.Since,
		arg.Until,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Pending,
			&i.Date,
			&i.Description,
			&i.Payee,
			&i.Memo,
			&i.SyncedAt,
			&i.Labels,
			&i.Extensions,
			&i.Source,
			&i.Relationships,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionExtensions = `-- name: UpdateTransactionExtensions :execrows
UPDATE transactions SET extensions = $1 WHERE id = $2
`

type UpdateTransactionExtensionsParams struct {
	Extensions string `json:"extensions"`
	ID         string `json:"id"`
}

// Replaces the whole schema-extensions object for one transaction. extensions is
// a JSON object of namespaced key->arbitrary-JSON-value pairs; the API normalizes
// it before storing. :execrows lets the caller detect a missing id (0 rows
// affected). The poller never touches extensions, so this is the only writer.
func (q *Queries) UpdateTransactionExtensions(ctx context.Context, arg UpdateTransactionExtensionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTransactionExtensions, arg.Extensions, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTransactionFromSync = `-- name: UpdateTransactionFromSync :execrows
UPDATE transactions
SET account_id  = $1,
    amount      = $2,
    pending     = $3,
    date        = $4,
    description = $5,
    payee       = $6,
    memo        = $7,
    synced_at   = $8
WHERE id = $9
`

type UpdateTransactionFromSyncParams struct {
	AccountID   string `json:"account_id"`
	Amount      string `json:"amount"`
	Pending     int64  `json:"pending"`
	Date        int64  `json:"date"`
	Description string `json:"description"`
	Payee       string `json:"payee"`
	Memo        string `json:"memo"`
	SyncedAt    int64  `json:"synced_at"`
	ID          string `json:"id"`
}

// Refreshes the bridge-owned fields of an existing transaction on re-sync (e.g. a
// pending charge that has now posted, or a corrected amount). labels, extensions,
// and source are intentionally NOT in the SET list: user metadata is never
// clobbered, and source is immutable provenance set once at insert. The poller
// calls this only when InsertTransaction reports the row already existed
// (ON CONFLICT DO NOTHING affected 0 rows).
func (q *Queries) UpdateTransactionFromSync(ctx context.Context, arg UpdateTransactionFromSyncParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTransactionFromSync,
		arg.AccountID,
		arg.Amount,
		arg.Pending,
		arg.Date,
		arg.Description,
		arg.Payee,
		arg.Memo,
		arg.SyncedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTransactionLabels = `-- name: UpdateTransactionLabels :execrows
UPDATE transactions SET labels = $1 WHERE id = $2
`

type UpdateTransactionLabelsParams struct {
	Labels string `json:"labels"`
	ID     string `json:"id"`
}

// Replaces the whole label set for one transaction. labels is a JSON object of
// key->value pairs; the API normalizes it before storing. :execrows lets the
// caller detect a missing id (0 rows affected). The poller never touches labels,
// so this is the only writer.
func (q *Queries) UpdateTransactionLabels(ctx context.Context, arg UpdateTransactionLabelsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTransactionLabels, arg.Labels, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTransactionRelationships = `-- name: UpdateTransactionRelationships :execrows
UPDATE transactions SET relationships = $1 WHERE id = $2
`

type UpdateTransactionRelationshipsParams struct {
	Relationships string `json:"relationships"`
	ID            string `json:"id"`
}

// Replaces the whole relationships array for one transaction. relationships is a
// JSON array of {"kind","target"} edges asserted outbound from this row; the API
// normalizes it before storing. :execrows lets the caller detect a missing id
// (0 rows affected). The poller never touches relationships, so this is the only
// writer.
func (q *Queries) UpdateTransactionRelationships(ctx context.Context, arg UpdateTransactionRelationshipsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTransactionRelationships, arg.Relationships, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
