// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
)

const getAccount = `-- name: GetAccount :one
SELECT id, org_id, name, currency, balance, balance_date, synced_at FROM accounts
WHERE id = ?1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.BalanceDate,
		&i.SyncedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, org_id, name, currency, balance, balance_date, synced_at FROM accounts
ORDER BY name
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Currency,
			&i.Balance,
			&i.BalanceDate,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByOrg = `-- name: ListAccountsByOrg :many
SELECT id, org_id, name, currency, balance, balance_date, synced_at FROM accounts
WHERE org_id = ?1
ORDER BY name
`

func (q *Queries) ListAccountsByOrg(ctx context.Context, orgID string) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Currency,
			&i.Balance,
			&i.BalanceDate,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO accounts (id, org_id, name, currency, balance, balance_date, synced_at)
VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7
)
ON CONFLICT (id) DO UPDATE SET
    org_id       = excluded.org_id,
    name         = excluded.name,
    currency     = excluded.currency,
    balance      = excluded.balance,
    balance_date = excluded.balance_date,
    synced_at    = excluded.synced_at
`

type UpsertAccountParams struct {
	ID          string `json:"id"`
	OrgID       string `json:"org_id"`
	Name        string `json:"name"`
	Currency    string `json:"currency"`
	Balance     string `json:"balance"`
	BalanceDate int64  `json:"balance_date"`
	SyncedAt    int64  `json:"synced_at"`
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccount,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Currency,
		arg.Balance,
		arg.BalanceDate,
		arg.SyncedAt,
	)
	return err
}
