// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package db

import (
	"context"
)

const deleteLabelByKey = `-- name: DeleteLabelByKey :execrows
UPDATE transactions
SET labels = json_remove(labels, '$."' || CAST(?1 AS TEXT) || '"')
WHERE json_extract(labels, '$."' || CAST(?1 AS TEXT) || '"') IS NOT NULL
`

// Removes one key from every transaction that carries it.
func (q *Queries) DeleteLabelByKey(ctx context.Context, labelKey string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLabelByKey, labelKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLabelByValue = `-- name: DeleteLabelByValue :execrows
UPDATE transactions
SET labels = json_remove(labels, '$."' || CAST(?1 AS TEXT) || '"')
WHERE json_extract(labels, '$."' || CAST(?1 AS TEXT) || '"') = ?2
`

type DeleteLabelByValueParams struct {
	LabelKey   string `json:"label_key"`
	LabelValue string `json:"label_value"`
}

// Removes the key only from transactions where it holds the given value (one
// value per key, so removing the key on a value match drops exactly that pair).
func (q *Queries) DeleteLabelByValue(ctx context.Context, arg DeleteLabelByValueParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLabelByValue, arg.LabelKey, arg.LabelValue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const filterTransactionsByLabelKey = `-- name: FilterTransactionsByLabelKey :many

SELECT id, account_id, amount, pending, date, description, payee, memo, synced_at, labels, extensions FROM transactions
WHERE json_extract(labels, '$."' || CAST(?1 AS TEXT) || '"') IS NOT NULL
  AND (account_id = ?2 OR ?2 = '')
  AND (date >= ?3 OR ?3 = 0)
  AND (date <= ?4 OR ?4 = 0)
ORDER BY date DESC, id
LIMIT ?6 OFFSET ?5
`

type FilterTransactionsByLabelKeyParams struct {
	LabelKey  string `json:"label_key"`
	AccountID string `json:"account_id"`
	Since     int64  `json:"since"`
	Until     int64  `json:"until"`
	RowOffset int64  `json:"row_offset"`
	RowLimit  int64  `json:"row_limit"`
}

// SQLite-specific label queries. Labels are a JSON object (key->value) stored in
// the TEXT `labels` column; these push filtering and deletion down to SQL via
// SQLite's JSON1 functions.
//
// Why json_extract with a built path rather than the `->>` operator: SQLite's
// `->>` only resolves its right operand as an object label when that operand is a
// string LITERAL. With a bound parameter it is treated as a JSON path and fails
// to match, so we build a quoted path (`$."<key>"`) explicitly. The quotes also
// make arbitrary keys (dots, spaces) safe; the API strips `"`/`\` from keys.
// CAST(... AS TEXT) keeps the key parameter a non-null string (a bare `||`
// operand is inferred nullable by sqlc).
func (q *Queries) FilterTransactionsByLabelKey(ctx context.Context, arg FilterTransactionsByLabelKeyParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, filterTransactionsByLabelKey,
		arg.LabelKey,
		arg.AccountID,
		arg.Since,
		arg.Until,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Pending,
			&i.Date,
			&i.Description,
			&i.Payee,
			&i.Memo,
			&i.SyncedAt,
			&i.Labels,
			&i.Extensions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterTransactionsByLabelValue = `-- name: FilterTransactionsByLabelValue :many
SELECT id, account_id, amount, pending, date, description, payee, memo, synced_at, labels, extensions FROM transactions
WHERE json_extract(labels, '$."' || CAST(?1 AS TEXT) || '"') = ?2
  AND (account_id = ?3 OR ?3 = '')
  AND (date >= ?4 OR ?4 = 0)
  AND (date <= ?5 OR ?5 = 0)
ORDER BY date DESC, id
LIMIT ?7 OFFSET ?6
`

type FilterTransactionsByLabelValueParams struct {
	LabelKey   string `json:"label_key"`
	LabelValue string `json:"label_value"`
	AccountID  string `json:"account_id"`
	Since      int64  `json:"since"`
	Until      int64  `json:"until"`
	RowOffset  int64  `json:"row_offset"`
	RowLimit   int64  `json:"row_limit"`
}

func (q *Queries) FilterTransactionsByLabelValue(ctx context.Context, arg FilterTransactionsByLabelValueParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, filterTransactionsByLabelValue,
		arg.LabelKey,
		arg.LabelValue,
		arg.AccountID,
		arg.Since,
		arg.Until,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Pending,
			&i.Date,
			&i.Description,
			&i.Payee,
			&i.Memo,
			&i.SyncedAt,
			&i.Labels,
			&i.Extensions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
