// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Account struct {
	ID          string `json:"id"`
	OrgID       string `json:"org_id"`
	Name        string `json:"name"`
	Currency    string `json:"currency"`
	Balance     string `json:"balance"`
	BalanceDate int64  `json:"balance_date"`
	SyncedAt    int64  `json:"synced_at"`
}

type Event struct {
	ID         int64  `json:"id"`
	EventID    string `json:"event_id"`
	EventType  string `json:"event_type"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	OccurredAt int64  `json:"occurred_at"`
	Data       string `json:"data"`
}

type Organization struct {
	ID      string `json:"id"`
	Domain  string `json:"domain"`
	Name    string `json:"name"`
	SfinUrl string `json:"sfin_url"`
}

type Rule struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Query     string `json:"query"`
	Labels    string `json:"labels"`
	Enabled   int64  `json:"enabled"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type SyncLog struct {
	ID          int64          `json:"id"`
	StartedAt   int64          `json:"started_at"`
	CompletedAt sql.NullInt64  `json:"completed_at"`
	Status      string         `json:"status"`
	Error       sql.NullString `json:"error"`
}

type Transaction struct {
	ID          string `json:"id"`
	AccountID   string `json:"account_id"`
	Amount      string `json:"amount"`
	Pending     int64  `json:"pending"`
	Date        int64  `json:"date"`
	Description string `json:"description"`
	Payee       string `json:"payee"`
	Memo        string `json:"memo"`
	SyncedAt    int64  `json:"synced_at"`
	Labels      string `json:"labels"`
}

type TransactionVersion struct {
	ID            int64  `json:"id"`
	TransactionID string `json:"transaction_id"`
	ChangeKind    string `json:"change_kind"`
	OccurredAt    int64  `json:"occurred_at"`
	Data          string `json:"data"`
}
