// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"
)

const getOrganization = `-- name: GetOrganization :one
SELECT id, domain, name, sfin_url FROM organizations
WHERE id = ?1
`

func (q *Queries) GetOrganization(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Name,
		&i.SfinUrl,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, domain, name, sfin_url FROM organizations
ORDER BY name
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Name,
			&i.SfinUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrganization = `-- name: UpsertOrganization :exec
INSERT INTO organizations (id, domain, name, sfin_url)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (id) DO UPDATE SET
    domain   = excluded.domain,
    name     = excluded.name,
    sfin_url = excluded.sfin_url
`

type UpsertOrganizationParams struct {
	ID      string `json:"id"`
	Domain  string `json:"domain"`
	Name    string `json:"name"`
	SfinUrl string `json:"sfin_url"`
}

func (q *Queries) UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, upsertOrganization,
		arg.ID,
		arg.Domain,
		arg.Name,
		arg.SfinUrl,
	)
	return err
}
