// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plugins.sql

package db

import (
	"context"
)

const deletePlugin = `-- name: DeletePlugin :execrows
DELETE FROM plugins WHERE id = ?1
`

func (q *Queries) DeletePlugin(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePlugin, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPlugin = `-- name: GetPlugin :one
SELECT id, name, runtime, version, enabled, granted_capabilities, config, created_at, updated_at, last_status, last_error, last_run_at, last_success_at FROM plugins WHERE id = ?1
`

func (q *Queries) GetPlugin(ctx context.Context, id int64) (Plugin, error) {
	row := q.db.QueryRowContext(ctx, getPlugin, id)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Runtime,
		&i.Version,
		&i.Enabled,
		&i.GrantedCapabilities,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastRunAt,
		&i.LastSuccessAt,
	)
	return i, err
}

const getPluginByName = `-- name: GetPluginByName :one
SELECT id, name, runtime, version, enabled, granted_capabilities, config, created_at, updated_at, last_status, last_error, last_run_at, last_success_at FROM plugins WHERE name = ?1
`

func (q *Queries) GetPluginByName(ctx context.Context, name string) (Plugin, error) {
	row := q.db.QueryRowContext(ctx, getPluginByName, name)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Runtime,
		&i.Version,
		&i.Enabled,
		&i.GrantedCapabilities,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastRunAt,
		&i.LastSuccessAt,
	)
	return i, err
}

const insertPlugin = `-- name: InsertPlugin :one
INSERT INTO plugins (name, runtime, version, enabled, granted_capabilities, config, created_at, updated_at)
VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8
)
RETURNING id, name, runtime, version, enabled, granted_capabilities, config, created_at, updated_at, last_status, last_error, last_run_at, last_success_at
`

type InsertPluginParams struct {
	Name                string `json:"name"`
	Runtime             string `json:"runtime"`
	Version             string `json:"version"`
	Enabled             int64  `json:"enabled"`
	GrantedCapabilities string `json:"granted_capabilities"`
	Config              string `json:"config"`
	CreatedAt           int64  `json:"created_at"`
	UpdatedAt           int64  `json:"updated_at"`
}

// Registers a newly-discovered plugin. Discovery seeds granted_capabilities from
// the manifest's requested set; enabled defaults to 0 (running third-party code is
// opt-in). RETURNING * yields the generated id and timestamps.
func (q *Queries) InsertPlugin(ctx context.Context, arg InsertPluginParams) (Plugin, error) {
	row := q.db.QueryRowContext(ctx, insertPlugin,
		arg.Name,
		arg.Runtime,
		arg.Version,
		arg.Enabled,
		arg.GrantedCapabilities,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Runtime,
		&i.Version,
		&i.Enabled,
		&i.GrantedCapabilities,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastRunAt,
		&i.LastSuccessAt,
	)
	return i, err
}

const listEnabledPlugins = `-- name: ListEnabledPlugins :many
SELECT id, name, runtime, version, enabled, granted_capabilities, config, created_at, updated_at, last_status, last_error, last_run_at, last_success_at FROM plugins WHERE enabled = 1 ORDER BY name
`

func (q *Queries) ListEnabledPlugins(ctx context.Context) ([]Plugin, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plugin{}
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Runtime,
			&i.Version,
			&i.Enabled,
			&i.GrantedCapabilities,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastStatus,
			&i.LastError,
			&i.LastRunAt,
			&i.LastSuccessAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlugins = `-- name: ListPlugins :many
SELECT id, name, runtime, version, enabled, granted_capabilities, config, created_at, updated_at, last_status, last_error, last_run_at, last_success_at FROM plugins ORDER BY name
`

func (q *Queries) ListPlugins(ctx context.Context) ([]Plugin, error) {
	rows, err := q.db.QueryContext(ctx, listPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plugin{}
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Runtime,
			&i.Version,
			&i.Enabled,
			&i.GrantedCapabilities,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastStatus,
			&i.LastError,
			&i.LastRunAt,
			&i.LastSuccessAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPluginEnabled = `-- name: SetPluginEnabled :execrows
UPDATE plugins SET enabled = ?1, updated_at = ?2 WHERE id = ?3
`

type SetPluginEnabledParams struct {
	Enabled   int64 `json:"enabled"`
	UpdatedAt int64 `json:"updated_at"`
	ID        int64 `json:"id"`
}

// Toggles execution. :execrows lets the caller detect a missing id.
func (q *Queries) SetPluginEnabled(ctx context.Context, arg SetPluginEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPluginEnabled, arg.Enabled, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginConfig = `-- name: UpdatePluginConfig :execrows
UPDATE plugins SET config = ?1, updated_at = ?2 WHERE id = ?3
`

type UpdatePluginConfigParams struct {
	Config    string `json:"config"`
	UpdatedAt int64  `json:"updated_at"`
	ID        int64  `json:"id"`
}

// Sets the operator config overrides (a JSON object merged over the manifest's).
func (q *Queries) UpdatePluginConfig(ctx context.Context, arg UpdatePluginConfigParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginConfig, arg.Config, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginGrantedCapabilities = `-- name: UpdatePluginGrantedCapabilities :execrows
UPDATE plugins
SET granted_capabilities = ?1, updated_at = ?2
WHERE id = ?3
`

type UpdatePluginGrantedCapabilitiesParams struct {
	GrantedCapabilities string `json:"granted_capabilities"`
	UpdatedAt           int64  `json:"updated_at"`
	ID                  int64  `json:"id"`
}

// Sets the approved capability grant (the marketplace approval flow writes this).
func (q *Queries) UpdatePluginGrantedCapabilities(ctx context.Context, arg UpdatePluginGrantedCapabilitiesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginGrantedCapabilities, arg.GrantedCapabilities, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginManifest = `-- name: UpdatePluginManifest :execrows
UPDATE plugins
SET runtime = ?1, version = ?2, updated_at = ?3
WHERE id = ?4
`

type UpdatePluginManifestParams struct {
	Runtime   string `json:"runtime"`
	Version   string `json:"version"`
	UpdatedAt int64  `json:"updated_at"`
	ID        int64  `json:"id"`
}

// Refreshes the manifest-derived fields on re-discovery WITHOUT touching operator
// state (enabled, granted_capabilities, config).
func (q *Queries) UpdatePluginManifest(ctx context.Context, arg UpdatePluginManifestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginManifest,
		arg.Runtime,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginRunStatus = `-- name: UpdatePluginRunStatus :exec
UPDATE plugins
SET last_status     = ?1,
    last_error      = ?2,
    last_run_at     = ?3,
    last_success_at = ?4
WHERE id = ?5
`

type UpdatePluginRunStatusParams struct {
	LastStatus    int64  `json:"last_status"`
	LastError     string `json:"last_error"`
	LastRunAt     int64  `json:"last_run_at"`
	LastSuccessAt int64  `json:"last_success_at"`
	ID            int64  `json:"id"`
}

// Records the outcome of the most recent hook invocation on the plugin row (the
// lean alternative to a per-invocation table). last_success_at is only advanced on
// a successful run; the caller passes the existing value otherwise.
func (q *Queries) UpdatePluginRunStatus(ctx context.Context, arg UpdatePluginRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePluginRunStatus,
		arg.LastStatus,
		arg.LastError,
		arg.LastRunAt,
		arg.LastSuccessAt,
		arg.ID,
	)
	return err
}
