// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CompleteSyncLog(ctx context.Context, arg CompleteSyncLogParams) error
	// Whether a transaction has any history yet. Backs the lazy baseline: the first
	// time an existing transaction changes after this feature shipped, the writer
	// synthesizes a v1 "imported" snapshot from its prior state. COUNT(*) is used (not
	// an EXISTS/MAX) because sqlc infers it as int64 identically on SQLite and Postgres
	// (see CountTransactions), keeping the pgstore adapter a plain pass-through.
	CountTransactionVersions(ctx context.Context, transactionID string) (int64, error)
	CountTransactions(ctx context.Context) (int64, error)
	// A rule pairs a condition (a kasas search query) with an action (a JSON object
	// of labels to apply on a match). The API validates the query and normalizes the
	// labels before storing. RETURNING * yields the generated id and timestamps.
	CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error)
	CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (SyncLog, error)
	// Retention prune: drops events that occurred before the cutoff (unix seconds).
	// :execrows reports how many rows were removed, for logging.
	DeleteEventsBefore(ctx context.Context, cutoff int64) (int64, error)
	// Removes one key from every transaction that carries it.
	DeleteLabelByKey(ctx context.Context, labelKey string) (int64, error)
	// Removes the key only from transactions where it holds the given value (one
	// value per key, so removing the key on a value match drops exactly that pair).
	DeleteLabelByValue(ctx context.Context, arg DeleteLabelByValueParams) (int64, error)
	DeleteRule(ctx context.Context, id int64) (int64, error)
	// Retention prune: drops versions that occurred before the cutoff (unix seconds).
	// :execrows reports how many rows were removed, for logging. Only runs when
	// events.history_retention_days > 0; the default keeps history forever.
	DeleteTransactionVersionsBefore(ctx context.Context, cutoff int64) (int64, error)
	// SQLite-specific label queries. Labels are a JSON object (key->value) stored in
	// the TEXT `labels` column; these push filtering and deletion down to SQL via
	// SQLite's JSON1 functions.
	//
	// Why json_extract with a built path rather than the `->>` operator: SQLite's
	// `->>` only resolves its right operand as an object label when that operand is a
	// string LITERAL. With a bound parameter it is treated as a JSON path and fails
	// to match, so we build a quoted path (`$."<key>"`) explicitly. The quotes also
	// make arbitrary keys (dots, spaces) safe; the API strips `"`/`\` from keys.
	// CAST(... AS TEXT) keeps the key parameter a non-null string (a bare `||`
	// operand is inferred nullable by sqlc).
	FilterTransactionsByLabelKey(ctx context.Context, arg FilterTransactionsByLabelKeyParams) ([]Transaction, error)
	FilterTransactionsByLabelValue(ctx context.Context, arg FilterTransactionsByLabelValueParams) ([]Transaction, error)
	GetAccount(ctx context.Context, id string) (Account, error)
	GetEventBySequence(ctx context.Context, id int64) (Event, error)
	GetOrganization(ctx context.Context, id string) (Organization, error)
	GetRule(ctx context.Context, id int64) (Rule, error)
	GetTransaction(ctx context.Context, id string) (Transaction, error)
	// Appends one immutable event to the canonical stream. The generated id
	// (sequence) and the stored row are returned so the caller can broadcast the
	// just-committed event to live SSE subscribers. event_id is a caller-supplied
	// UUID (unique); data is a JSON object.
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	// transactions.id is the SimpleFIN transaction ID, so re-syncing the same
	// transaction is a no-op. This keeps polling idempotent. labels is written as an
	// explicit empty object so new rows never depend on the column default (SQLite
	// can't cheaply change a STRICT table's default; see the 00003 migration).
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error)
	// Appends one immutable snapshot to a transaction's history. The generated id
	// (insert order) and the stored row are returned. There is no per-transaction
	// version number column: a transaction's versions are its rows ordered by id, and
	// the API assigns the ordinal (v1, v2, ...) on read. data is a JSON object.
	InsertTransactionVersion(ctx context.Context, arg InsertTransactionVersionParams) (TransactionVersion, error)
	LatestSyncLog(ctx context.Context) (SyncLog, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListAccountsByOrg(ctx context.Context, orgID string) ([]Account, error)
	// The deterministic id order makes rule precedence predictable when several
	// rules write the same label key (later rules win).
	ListEnabledRules(ctx context.Context) ([]Rule, error)
	// The cursor read: every event whose sequence is greater than `after`, in stream
	// order, with optional exact-match filters (an empty string disables that filter).
	// Mirrors the ListTransactions optional-filter shape - the column is written first
	// so sqlc infers a non-null type for each bound parameter, keeping the generated
	// params struct byte-identical across SQLite and Postgres (row_limit aside, which
	// the pg adapter casts to int32). row_limit caps the page size.
	ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error)
	// Returns the (id, labels) of every transaction that carries at least one label.
	// The API explodes the JSON objects in Go to build the label vocabulary with
	// per-pair transaction counts. Done in Go (not SQL) to stay portable across
	// SQLite and Postgres: json_each (SQLite) and jsonb_each_text (Postgres) infer
	// different column types, which would break the byte-identical pgstore adapter.
	// Filtering and deletion, by contrast, are pushed down to SQL (see the
	// per-dialect queries/{sqlite,postgres}/labels.sql). ORDER BY makes the row order
	// deterministic.
	ListLabeledTransactions(ctx context.Context) ([]ListLabeledTransactionsRow, error)
	ListOrganizations(ctx context.Context) ([]Organization, error)
	// The most recent events, newest first. Powers "what just happened" views (the
	// dashboard live feed) that want the tail of the stream without first discovering
	// its head. Callers that want chronological order reverse the result.
	ListRecentEvents(ctx context.Context, rowLimit int64) ([]Event, error)
	ListRules(ctx context.Context) ([]Rule, error)
	ListSyncLogs(ctx context.Context, rowLimit int64) ([]SyncLog, error)
	// One transaction's full history, oldest first. ORDER BY id is the version order
	// (id is the monotonic insert sequence), so the caller assigns v1, v2, ... by
	// position and diffs each snapshot against the previous one.
	ListTransactionVersions(ctx context.Context, transactionID string) ([]TransactionVersion, error)
	// A bound of 0 disables that side of the date filter (so 0/0 returns all).
	// The column comparison is written first so sqlc infers an integer type for
	// the bound parameters from the `date` column.
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]Transaction, error)
	// Replaces the editable fields of a rule. :execrows lets the caller detect a
	// missing id (0 rows affected).
	UpdateRule(ctx context.Context, arg UpdateRuleParams) (int64, error)
	// Refreshes the bridge-owned fields of an existing transaction on re-sync (e.g. a
	// pending charge that has now posted, or a corrected amount). labels is
	// intentionally NOT in the SET list, so user labels are never clobbered. The
	// poller calls this only when InsertTransaction reports the row already existed
	// (ON CONFLICT DO NOTHING affected 0 rows).
	UpdateTransactionFromSync(ctx context.Context, arg UpdateTransactionFromSyncParams) (int64, error)
	// Replaces the whole label set for one transaction. labels is a JSON object of
	// key->value pairs; the API normalizes it before storing. :execrows lets the
	// caller detect a missing id (0 rows affected). The poller never touches labels,
	// so this is the only writer.
	UpdateTransactionLabels(ctx context.Context, arg UpdateTransactionLabelsParams) (int64, error)
	UpsertAccount(ctx context.Context, arg UpsertAccountParams) error
	UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) error
}

var _ Querier = (*Queries)(nil)
