// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_log.sql

package db

import (
	"context"
	"database/sql"
)

const completeSyncLog = `-- name: CompleteSyncLog :exec
UPDATE sync_log
SET completed_at = ?1,
    status       = ?2,
    error        = ?3
WHERE id = ?4
`

type CompleteSyncLogParams struct {
	CompletedAt sql.NullInt64  `json:"completed_at"`
	Status      string         `json:"status"`
	Error       sql.NullString `json:"error"`
	ID          int64          `json:"id"`
}

func (q *Queries) CompleteSyncLog(ctx context.Context, arg CompleteSyncLogParams) error {
	_, err := q.db.ExecContext(ctx, completeSyncLog,
		arg.CompletedAt,
		arg.Status,
		arg.Error,
		arg.ID,
	)
	return err
}

const createSyncLog = `-- name: CreateSyncLog :one
INSERT INTO sync_log (started_at, status)
VALUES (?1, ?2)
RETURNING id, started_at, completed_at, status, error
`

type CreateSyncLogParams struct {
	StartedAt int64  `json:"started_at"`
	Status    string `json:"status"`
}

func (q *Queries) CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (SyncLog, error) {
	row := q.db.QueryRowContext(ctx, createSyncLog, arg.StartedAt, arg.Status)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const latestSyncLog = `-- name: LatestSyncLog :one
SELECT id, started_at, completed_at, status, error FROM sync_log
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) LatestSyncLog(ctx context.Context) (SyncLog, error) {
	row := q.db.QueryRowContext(ctx, latestSyncLog)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const listSyncLogs = `-- name: ListSyncLogs :many
SELECT id, started_at, completed_at, status, error FROM sync_log
ORDER BY started_at DESC
LIMIT ?1
`

func (q *Queries) ListSyncLogs(ctx context.Context, rowLimit int64) ([]SyncLog, error) {
	rows, err := q.db.QueryContext(ctx, listSyncLogs, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncLog{}
	for rows.Next() {
		var i SyncLog
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
