// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"
)

const deleteWebhook = `-- name: DeleteWebhook :execrows
DELETE FROM webhooks WHERE id = ?1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWebhook, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, url, secret, event_types, enabled, created_at, updated_at, last_status, last_error, last_attempt_at, last_success_at FROM webhooks WHERE id = ?1
`

func (q *Queries) GetWebhook(ctx context.Context, id int64) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Secret,
		&i.EventTypes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastAttemptAt,
		&i.LastSuccessAt,
	)
	return i, err
}

const insertWebhook = `-- name: InsertWebhook :one
INSERT INTO webhooks (url, secret, event_types, enabled, created_at, updated_at)
VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6
)
RETURNING id, url, secret, event_types, enabled, created_at, updated_at, last_status, last_error, last_attempt_at, last_success_at
`

type InsertWebhookParams struct {
	Url        string `json:"url"`
	Secret     string `json:"secret"`
	EventTypes string `json:"event_types"`
	Enabled    int64  `json:"enabled"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

// Registers a webhook endpoint. `event_types` is a JSON array string of subscribed
// types ('[]'/'["*"]' = all). RETURNING * yields the generated id and timestamps.
func (q *Queries) InsertWebhook(ctx context.Context, arg InsertWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, insertWebhook,
		arg.Url,
		arg.Secret,
		arg.EventTypes,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Secret,
		&i.EventTypes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastAttemptAt,
		&i.LastSuccessAt,
	)
	return i, err
}

const listEnabledWebhooks = `-- name: ListEnabledWebhooks :many
SELECT id, url, secret, event_types, enabled, created_at, updated_at, last_status, last_error, last_attempt_at, last_success_at FROM webhooks WHERE enabled = 1 ORDER BY id
`

// The dispatcher loads this set on each event and filters by type in Go.
func (q *Queries) ListEnabledWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Secret,
			&i.EventTypes,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastStatus,
			&i.LastError,
			&i.LastAttemptAt,
			&i.LastSuccessAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, url, secret, event_types, enabled, created_at, updated_at, last_status, last_error, last_attempt_at, last_success_at FROM webhooks ORDER BY id
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Secret,
			&i.EventTypes,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastStatus,
			&i.LastError,
			&i.LastAttemptAt,
			&i.LastSuccessAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :execrows
UPDATE webhooks
SET url         = ?1,
    event_types = ?2,
    enabled     = ?3,
    updated_at  = ?4
WHERE id = ?5
`

type UpdateWebhookParams struct {
	Url        string `json:"url"`
	EventTypes string `json:"event_types"`
	Enabled    int64  `json:"enabled"`
	UpdatedAt  int64  `json:"updated_at"`
	ID         int64  `json:"id"`
}

// Replaces the editable fields. :execrows lets the caller detect a missing id.
func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWebhook,
		arg.Url,
		arg.EventTypes,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWebhookDeliveryStatus = `-- name: UpdateWebhookDeliveryStatus :exec
UPDATE webhooks
SET last_status     = ?1,
    last_error      = ?2,
    last_attempt_at = ?3,
    last_success_at = ?4
WHERE id = ?5
`

type UpdateWebhookDeliveryStatusParams struct {
	LastStatus    int64  `json:"last_status"`
	LastError     string `json:"last_error"`
	LastAttemptAt int64  `json:"last_attempt_at"`
	LastSuccessAt int64  `json:"last_success_at"`
	ID            int64  `json:"id"`
}

// Records the outcome of the most recent delivery attempt on the webhook row (the
// lean alternative to a per-delivery table). last_success_at is only advanced on a
// 2xx; the caller passes the existing value otherwise.
func (q *Queries) UpdateWebhookDeliveryStatus(ctx context.Context, arg UpdateWebhookDeliveryStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookDeliveryStatus,
		arg.LastStatus,
		arg.LastError,
		arg.LastAttemptAt,
		arg.LastSuccessAt,
		arg.ID,
	)
	return err
}

const updateWebhookSecret = `-- name: UpdateWebhookSecret :execrows
UPDATE webhooks
SET secret = ?1, updated_at = ?2
WHERE id = ?3
`

type UpdateWebhookSecretParams struct {
	Secret    string `json:"secret"`
	UpdatedAt int64  `json:"updated_at"`
	ID        int64  `json:"id"`
}

// Rotates the signing secret (and bumps updated_at).
func (q *Queries) UpdateWebhookSecret(ctx context.Context, arg UpdateWebhookSecretParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWebhookSecret, arg.Secret, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
